#!/usr/bin/env bash

# start X server, and wait for it to come up enough to answer a query
(xdpyinfo > /dev/null) || exit 1

IP=$(ifconfig en0 | grep inet | awk '$1=="inet" {print $2}')
TDIR=/tmp/firefox-nightly
XAUTH=$TDIR/.Xauthority
COOKIE=`xauth list :0 | awk '{print $3}'`

mkdir -p $TDIR/.config/pulse
touch $XAUTH
xauth -f $XAUTH add $IP:0 . $COOKIE

if hash pactl 2>/dev/null; then
  pactl info > /dev/null  # hope this is synchronous
  pactl load-module module-esound-protocol-tcp > /dev/null
  pactl load-module module-native-protocol-tcp > /dev/null
  cp $HOME/.config/pulse/cookie $TDIR/.config/pulse/cookie
  PULSE_SERVER=$IP
else
  echo "to enable sound: 'brew install pulseaudio'"
fi

docker run --name firefox-nightly -it --rm \
  -v $TDIR:$TDIR \
  -e DISPLAY=$IP:0 \
  -e PULSE_SERVER=$PULSE_SERVER \
  -e XAUTHORITY=$XAUTH \
  --user $UID:$GID \
  hildjj/firefox-nightly:latest "$@"
